version: "3.8"

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aloom-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    depends_on:
      - db
      - mongo
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=aloom-db
      - MONGO_URI=mongodb://mongo:27017/aloom-mongo
    ports:
      - "3000:3000"
    command: ./entrypoint.sh
    volumes:
      - .:/usr/src/app

volumes:
  postgres-data:
  mongo-data:
  # prom_data:
  # grafana-data:

  # prometheus:
  #   image: prom/prometheus
  #   container_name: aloom-prometheus
  #   command:
  #     - "--config.file=/etc/prometheus/prometheus.yml"
  #   ports:
  #     - 9090:9090
  #   restart: unless-stopped
  #   volumes:
  #     - ./prometheus:/etc/prometheus
  #     - prom_data:/prometheus

  #   depends_on:
  #     - api

  # grafana:
  #   image: grafana/grafana
  #   container_name: aloom-grafana
  #   ports:
  #     - "3001:3000" # Expose Grafana on port 3001 to avoid conflicts
  #   environment:
  #     - GF_SECURITY_ADMIN_USER=admin
  #     - GF_SECURITY_ADMIN_PASSWORD=admin
  #   volumes:
  #     - grafana-data:/var/lib/grafana
  #   depends_on:
  #     - prometheus
